#!/usr/bin/env bash
set -euo pipefail

[ "$#" -ge 2 ] || { echo "Usage: $0 <lab_folder> <question> [args<>]"; exit 1; }

Folder="$1"
Question="$2"
shift 2
   
javac -d . "$Folder"/*.java

java -cp . "${Folder}.${Question}" "$@"
